### PR TITLE
Resolves #50

### LINKED ISSUE #50: Add scripts to check if formatting is ok in mobile and api
Would be useful to ensure formatting is good before making a pull request

### PR DESCRIPTION
**Pull request by zusoomro**

### CODE REVIEW

**Review by allysmith12 — COMMENTED** [review]
LGTM!

**Review by allysmith12 — APPROVED** [review]
LGTM

**Comment by allysmith12** [comment]
Zulfi what is this? Does it need to be merged or deleted?

**Comment by zusoomro** [comment]
Ya I'm just gonna close it - it added some formatting scripts but looks like we have it under control.

**Pull request closed without merging**
