### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by zusoomro**

### CODE REVIEW

**Comment by zusoomro** [comment]
This PR adds a basic testing setup for the mobile app.

**Review by chloeprezelski — COMMENTED** [review]
Since at root in App.js we are calling loadUser(), is this going to be passed in props to subcomponents? Or should each component call loadUser when necessary? 

Also it looks like there are merge conflicts that need to be resolved.

**Review by chloeprezelski — APPROVED** [review]

**Comment by zusoomro** [comment]
When loadUser is called in the top level app, the user is stored in the redux store and can be accessed at any component. However, it is not passed through props, and has to be "selected" out of the global redux state. As it stands, this can be done this way.

```
const currentUser = useSelector(state => state.auth.user)
```

This will always update when the user changes, so currentUser will always have the most recent user information.

**Comment by zusoomro** [comment]
Essentially, loadUser is called once and then shouldn't need to be called again. If we make changes to the user object, we can do it client-side in the redux store, as well as relaying that information to the server via a post/put request. A pattern we are trying to avoid here is pushing changes to the server and then pinging the server for those same exact changes. Say for example we change a user's email. Instead of changing the email in a PUT request to the server and then calling loadUser again, we should just simultaneously change our representation of the user in the client-side redux store. So, loadUser probably shouldn't be called in more than once place in the app (or if we log a user out and log a new one in).

**Pull request merged**
